#:schema node_modules/wrangler/config-schema.json
name = "sturdyflour"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Required for Cloudflare Pages connection
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB" # Maps code access env.DB to production D1
database_name = "sturdyflour-db"
database_id = "5d8cee23-8988-4bab-92ae-51ad12c5f7f3"

[[r2_buckets]]
binding = "R2" # Maps code access env.R2 to production R2
bucket_name = "sturdyflour-storage"
